### ISSUE TITLE
I don't believe src/ is so common for python

### ISSUE THREAD

**Issue by kootenpv** [jlesquembre/autopilot#2]
It would be more common to have a structure like:

    autopilot/
       tests/
       autopilot/
           "code"
       README
       setup.py
       tox.ini
       ...
       ... 

Than to have:

    autopilot/
       tests/
       src/
          autopilot/
              "code"

**Comment by jlesquembre** [comment]
Some well know packages have this structure, like SQLAlchemy.

I agree that having your code under `src` is not so common, but I think it should be.

Take a look to this example:

https://github.com/ionelmc/python-packaging-blunders

In this example, if you install the no-src package with `pip install -e .`, you will be able to import setup.py and some_test_junk.py. But in the project with-src, you are not able to import that files.

You can also try it with one of your packages, https://github.com/kootenpv/yagmail . After a `pip install -e path/to/yagmail`, start a python interpreter and do a `import deploy`, it is executing your deploy.py script. Now, what happens if you want to install a package called deploy? Like for example https://pypi.python.org/pypi/deploy 


Another reason, is that if you want to distribute some extra files, probably you need to write and maintain a MANIFEST.in file, but maintaining it is not so easy, take a look to the rules:
https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute

For me, having all my files under a src directory makes it easier. But if you are using autopilot, you don't need to handle a `MANIFEST.in` file :-) See:

http://autopilot-docs.readthedocs.org/en/latest/choices.html#files-to-distribute

And probably there are more reasons, take a look to this link:
http://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure


Maybe the kind of mistakes we avoid with a `src` directory are not so common, and some people never are going to have them. But if there are less chances for mistakes by just creating an extra directory, why don't do it?

**Comment by kootenpv** [comment]
Nicely argumented, it is very convincing! Great to use a package of my own as an example; it is immediately clear.
